### ISSUE TITLE
ESP32 Espressif Improvements - Roadmap Summary

### ISSUE THREAD

**Issue by gojimmypi** [wolfSSL/wolfssl#6234]
### Version

Latest master branch

### Description

There are a large numbers of improvements in my [fork](https://github.com/gojimmypi/wolfssl/tree/ED25519_SHA2_fix) that not only address several open issues, but also include numerous other improvements, both Espressif-specific and general library updates.

The changes will be documented and managed in this separate issue. Many of them are interrelated, but some can be extracted into separate pull requests from [ED25519_SHA2_fix](https://github.com/gojimmypi/wolfssl/tree/ED25519_SHA2_fix):

## Actively working on:
 
- [ ] https://github.com/wolfSSL/wolfssl/issues/7640 see also [esp-idf #13966](https://github.com/espressif/esp-idf/issues/13966)
- [ ] https://github.com/wolfSSL/wolfssl/issues/6848
- [ ] https://github.com/wolfSSL/wolfMQTT/issues/353
- [ ] https://github.com/wolfSSL/wolfssl/issues/6637
- [ ] https://github.com/wolfSSL/wolfssl/pull/6609
- [ ] https://github.com/wolfSSL/wolfssl/issues/6681 (see [#6825](https://github.com/wolfSSL/wolfssl/pull/6825))

## Issues:

- [ ] https://github.com/wolfSSL/wolfssl/issues/6118.
- [ ] https://github.com/wolfSSL/wolfssl/issues/6025.
- [ ] https://github.com/wolfSSL/wolfssl/issues/5989.
- [ ] https://github.com/wolfSSL/wolfssl/issues/5727.
- [ ] https://github.com/wolfSSL/wolfssl/issues/5154.
- [ ] https://github.com/wolfSSL/wolfssl-examples/issues/369

## Done, pending user acceptance:

- [ ] https://github.com/wolfSSL/wolfssl/issues/5909. See https://github.com/wolfSSL/wolfssl/issues/5909#issuecomment-1533288775
- [ ] https://github.com/wolfSSL/wolfssl/issues/6028.

## Pull Requests:

- [ ] https://github.com/wolfSSL/wolfssl/pull/6134.
- [ ] https://github.com/wolfSSL/wolfssl/pull/5998.
- [ ] https://github.com/wolfSSL/wolfssl/pull/5964.
- [ ] https://github.com/wolfSSL/wolfssl/pull/5950.
- [ ] https://github.com/wolfSSL/wolfssl/pull/5876.

## Espressif specific:

- [ ] Transfer [espressif/esp-wolfssl](https://github.com/espressif/esp-wolfssl) to wolfSSL.
- [ ] Add [the Github action](https://github.com/espressif/upload-components-ci-action) to upload the component to the registry into the esp-wolfssl repository. An example can be seen [here](https://github.com/espressif/esp32-camera/blob/master/.github/workflows/upload_component.yml).
- [ ] Update wolfssl​ submodule to one of the recent release tags.
- [ ] Remove the legacy GNU Make build system.
- [ ] Remove support for EoL versions of IDF.
- [ ] Port the CI scripts from Espressif Gitlab-based ones to Github Actions.
- [ ] Add a component version badge to README.
- [ ] Review and update the README as necessary.

## Espressif RISC-V:

- [ ] Implement wolfSSL Hardware Acceleration on the ESP32-C3, ESP32-C6, etc. 
- [ ] Add example core woldSSL RISC-V projects in [Espressif/ESP-IDF/examples](https://github.com/wolfSSL/wolfssl/tree/master/IDE/Espressif/ESP-IDF/examples).
- [ ] Add example RISC-V projects in [wolfssl-examples](https://github.com/wolfSSL/wolfssl-examples/tree/master/ESP32).
- [ ] Add example RISC-V projects in [wolfssh-examples](https://github.com/wolfSSL/wolfssh-examples/tree/main/Espressif).

## Espressif Arduino:

- [ ] https://github.com/wolfSSL/wolfssl/issues/6360

## Other Improvements:

- [ ] https://github.com/wolfSSL/wolfssl-examples/issues/385 
- [ ] https://github.com/wolfSSL/wolfssh/issues/514
- [ ] Update examples in [wolfssl-examples](https://github.com/wolfSSL/wolfssl-examples/tree/master/ESP32) to support ESP-IDF v5.
- [ ] Update SSH examples in [wolfssh-examples](https://github.com/wolfSSL/wolfssh-examples/tree/main/Espressif) to support ESP-IDF v5.
- [ ] Create a stand-alone ESP32 CSR Key/Sign Example from the [WIP #6205 Example](https://github.com/gojimmypi/wolfssl/tree/ED25519_SHA2_fix/IDE/Espressif/ESP-IDF5/examples/wolfssl_server_6205).
- [ ] Implement and expand KConfig support.
- [ ] Fix HW math acceleration in TFM. See interim fix in https://github.com/wolfSSL/wolfssl/pull/6286

## Mothballed, to address later:

- https://github.com/wolfSSL/wolfssl/pull/6825
- https://github.com/wolfSSL/wolfssl/issues/6681
- https://github.com/wolfSSL/wolfssl/issues/6385 (see [#6380](https://github.com/wolfSSL/wolfssl/issues/6380))
- https://github.com/wolfSSL/wolfssl/issues/6380 (fixed in [#6624]- https://github.com/wolfSSL/wolfssl/pull/6134
- [ ] https://github.com/wolfSSL/wolfssl/issues/6359
- https://github.com/wolfSSL/wolfssl/issues/6025
- https://github.com/wolfSSL/wolfssl/issues/5989
- https://github.com/wolfSSL/wolfssl/pull/5998
- https://github.com/wolfSSL/wolfssl/issues/5883.
- https://github.com/wolfSSL/wolfssl/pull/6149.  (see `esp_ShowExtendedSystemInfo` in [esp32-crypt.h](https://github.com/gojimmypi/wolfssl/blob/master/wolfssl/wolfcrypt/port/Espressif/esp32-crypt.h) ) 
(https://github.com/wolfSSL/wolfssl/pull/6624))
- 

## Done - wolfSSL
- [x] https://github.com/wolfSSL/wolfssl/pull/7067 
- [x] https://github.com/wolfSSL/wolfssl/issues/5319. See ([PR #6708](https://github.com/wolfSSL/wolfssl/pull/6708))
- [x] https://github.com/wolfSSL/wolfssl/pull/7037
- [x] https://github.com/wolfSSL/wolfssl/pull/7035
- [x] https://github.com/wolfSSL/wolfssl/pull/6990
- [x] https://github.com/wolfSSL/wolfssl/issues/6779
- [x] https://github.com/wolfSSL/wolfssl/pull/6811
- [x] https://github.com/wolfSSL/wolfssl/pull/6844
- [x] https://github.com/wolfSSL/wolfssl/issues/5948.
- [x] https://github.com/wolfSSL/wolfssl/issues/6375 (fixed in [#6624](https://github.com/wolfSSL/wolfssl/pull/6624))
- [x] https://github.com/wolfSSL/wolfssl/issues/6373
- [x] https://github.com/wolfSSL/wolfssl/pull/6374
- [x] https://github.com/wolfSSL/wolfssl/issues/6059.
- [x] https://github.com/wolfSSL/wolfssl/pull/6018
- [x] https://github.com/wolfSSL/wolfssl/pull/6682
- [x] https://github.com/wolfSSL/wolfssl/pull/6624
- [x] Confirm [wolfSSL works in namespace](https://components.espressif.com/components/wolfssl/wolfssl) in the ESP-IDF component registry, https://components.espressif.com/.
- [x] https://github.com/wolfSSL/wolfssl/pull/6210.
- [x] https://github.com/wolfSSL/wolfssl/pull/6624
- [x] https://github.com/wolfSSL/wolfssl/issues/6522 for ESP32-S3 Linux (fixed in #6523)
- [x] https://github.com/wolfSSL/wolfssl/pull/6523 
- [x] https://github.com/wolfSSL/wolfssl/pull/6587
- [x] https://github.com/wolfSSL/wolfssl/pull/6249.
- [x] https://github.com/wolfSSL/wolfssl/pull/6285
- [x] https://github.com/wolfSSL/wolfssl/pull/6287
- [x] https://github.com/wolfSSL/wolfssl/pull/6286 (fixed in [#6624](https://github.com/wolfSSL/wolfssl/pull/6624))
- [x] https://github.com/wolfSSL/wolfssl/issues/6205 (fixed in [#6624]
- [x] https://github.com/wolfSSL/wolfssl/issues/6163.
- [x] https://github.com/wolfSSL/wolfssl/issues/5215.

## Done - wolfSSH
- [x] https://github.com/wolfSSL/wolfssh/pull/589
- [x] https://github.com/wolfSSL/wolfssh/issues/588. See ([wolfSSH PR #601](https://github.com/wolfSSL/wolfssh/pull/601))

## Done - wolfMQTT

- [x] https://github.com/wolfSSL/wolfMQTT/issues/352

Have an idea for other improvements? Feel free to open a new issue or send us an email [facts@wolfssl.com](mailto:facts@wolfssl.com?subject=Feature%20Request)
